service: musinsa-serverless
frameworkVersion: '3'

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!python/**'
    - '!python.zip'
    - '!package-lock.json'
    - '!package.json'
    - '!README.md'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  stage: dev

layers:
  python:
    package:
      artifact: python.zip

constructs:
  deliver:
    type: queue
    worker:
      handler: functions/delivers.handler
      layers:
        - { Ref: PythonLambdaLayer }
      environment:
        QUEUE_URL: ${construct:result.queueUrl}
      package:
        patterns:
          - '!functions/results.py'
          - '!functions/returns.py'

  result:
    type: queue
    worker:
      handler: functions/results.handler
      layers:
        - { Ref: PythonLambdaLayer }
      environment:
        QUEUE_URL: ${construct:result.queueUrl}
      package:
        patterns:
          - '!functions/returns.py'
          - '!functions/delivers.py'

functions:
  return:
    handler: functions/returns.handler
    layers:
      - { Ref: PythonLambdaLayer }
    # events:
    #   - schedule: rate(1 minute)
    environment:
      QUEUE_URL: ${construct:deliver.queueUrl}
    package:
      patterns:
        - '!functions/results.py'
        - '!functions/delivers.py'

plugins:
  - serverless-lift
  - serverless-dotenv-plugin